config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
  resources :recomendacoes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "recomendacoes#index"

  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recomendacao.rb
class Recomendacao < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many: :recomendacao
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

end

app/controllers/recomendacoes_controller.rb
class RecomendacoesController < ApplicationController
  before_action :set_recomendacao, only: %i[ show edit update destroy ]

  # GET /recomendacoes or /recomendacoes.json
  def index
    @recomendacoes = Recomendacao.all
  end

  # GET /recomendacoes/1 or /recomendacoes/1.json
  def show
  end

  # GET /recomendacoes/new
  def new
    @recomendacao = Recomendacao.new
  end

  # GET /recomendacoes/1/edit
  def edit
  end

  # POST /recomendacoes or /recomendacoes.json
  def create
    @recomendacao = Recomendacao.new(recomendacao_params)

    respond_to do |format|
      if @recomendacao.save
        format.html { redirect_to recomendacao_url(@recomendacao), notice: "Recomendacao was successfully created." }
        format.json { render :show, status: :created, location: @recomendacao }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recomendacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recomendacoes/1 or /recomendacoes/1.json
  def update
    respond_to do |format|
      if @recomendacao.update(recomendacao_params)
        format.html { redirect_to recomendacao_url(@recomendacao), notice: "Recomendacao was successfully updated." }
        format.json { render :show, status: :ok, location: @recomendacao }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recomendacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recomendacoes/1 or /recomendacoes/1.json
  def destroy
    @recomendacao.destroy

    respond_to do |format|
      format.html { redirect_to recomendacoes_url, notice: "Recomendacao was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recomendacao
      @recomendacao = Recomendacao.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recomendacao_params
      params.require(:recomendacao).permit(:artista, :titulo, :img, :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recomendacoes_helper.rb
module RecomendacoesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>



<p class="navbar-text float-center">
<% if user_signed_in? %>
  Logado como: <strong><%= current_user.email %></strong>.
  <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>


 <title>Workspace</title>
 <%= stylesheet_link_tag 'application', media: 'all', 'dataturbolinks-track' => true %>
 
 <%= csrf_meta_tags %>
 <link rel="stylesheet"
href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.mi
n.css">
</head>
<body>

<p class="notice"><%= notice %></p> 
<p class="alert"><%= alert %></p> 

<%= yield %>
<script src="https://code.jquery.com/jquery3.2.1.slim.min.js"></script>
<script
src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/poppe
r.min.js"></script>

<script
src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.
js"></script>
</body>
</html>

app/views/recomendacoes/_form.html.erb
<link rel="stylesheet" type="text/css" href="style2.css">
<center><h2>A sua recomendação é importante para manter a plataforma :D</h2></center>
<%= form_with(model: recomendacao, local:true) do |form| %>
  <% if recomendacao.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recomendacao.errors.count, "error") %> prohibited this recomendacao from being saved:</h2>

      <ul>
        <% recomendacao.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
         <form id='survey-form'>
        <div class="container">
       <form id='survey-form'>
           <div class='form-input'>
               <label id='name-label'>Username</label>
               <%= form.text_field :artista, class:'form-input-size', placeholder: "Exemplo: 1uc4s_m4theus" %>
           </div>
           <div class='form-input'>
               <label id='email-label'>Álbum</label>
               <%= form.text_field :titulo, class:'form-input-size', placeholder: "Exemplo: Metalica - Master of Puppets" %>
           </div>

           <div class='form-input'>
               <label id='email-label'>Capa</label>
               <%= form.text_field :img, class:'form-input-size', placeholder: "www.google.com" %>
           </div>


           <div class='form-input'>
               <p>O que você pensa sobre esse álbum?  </p>
               <%= form.text_area :desc, class:'form-input-size', placeholder: "Deixe seu comentário sobre a recomendação" %>
           </div>

           <div class='form-input'>
               <button type='submit' id='submit' form.submit >Enviar</button>
                <%= %>
           </div>
           <div class='form-input'>

           <button id= 'come_back_button'>
                  <%= link_to "Ver Mural", recomendacoes_path, style: "color:white" %>
                </button>
            </div>
            </div>
       </form>
   </div>
   <% end %>

app/views/recomendacoes/_recomendacao.html.erb
<div id="<%= dom_id recomendacao %>">
  <p>
    <strong>Titulo:</strong>
    <%= recomendacao.titulo %>
  </p>

  <p>
    <strong>Artista:</strong>
    <%= recomendacao.artista %>
  </p>

  <p>
    <strong>Comentário</strong>
    <%= recomendacao.desc %>
  </p>

  <p>
    <strong>Capa</strong>
    <%= recomendacao.img %>
  </p>

</div>

app/views/recomendacoes/edit.html.erb
<h1>Editar Recomendações</h1>

<%= render "form", recomendacao: @recomendacao %>

<br>

<div>
  <%= link_to "Mostrar Recomendações", @recomendacao %> |
  <%= link_to "Voltar", recomendacoes_path %>
</div>

app/views/recomendacoes/index.html.erb
<p style="color: green"><%= notice %></p>




	

    
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&ampdisplay=swap" rel="stylesheet">


<style>
        body{
            background-color:black;
        }
        .album{
            width: 220px !important;
            position: relative !important;
            margin:0 auto !important;
            line-height: 1.4em !important;
            display: inline-block !important;
        }
        #name_album{
            font-size: 10px;
            color:white;
            word-wrap: normal;

        }
        .checked {
            color: orange;  
        }
        .icons2{
          width: 220px;
            position: relative;
            margin:0 auto;
            line-height: 1.4em;
            display: inline-block;

        }
        .image {
            width: 200px !important;
            position: relative !important;
            margin:0 auto !important;
            line-height: 1.4em !important;
            display: inline-block !important;
}

.image__img {
    display: block;
}

.image__overlay {
    position: absolute;
    top: 0;
    left: 0;
    width: 200px;
    height: 200px;
    background: rgba(0, 0, 0, 0.6);
    color: #ffffff;
    font-family: 'Quicksand', sans-serif;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    opacity: 0;
    transition: opacity 0.30s;
}

.image__overlay--blur {
    backdrop-filter: blur(5px);
}

.image__overlay--primary {
    background:black ;
}

.image__overlay2--primary {
    background: red;
}

.image__overlay > * {
    transform: translateY(20px);
    transition: transform 0.25s;
}

.image__overlay:hover {
    opacity: 1;
}

.image__overlay:hover > * {
    transform: translateY(0);
}

.image__title {
    font-size: 1em;
    font-weight: bold;
}

.image__description {
    font-size: 14px;
    margin-top: 0.25em;
}
</style>


<center><h1>Meu Mural</h1></center>
<br>
  <% @recomendacoes.each do |recomendacao| %>
    <div class="album">
    <p class="teste"> <%= link_to "", recomendacao%> <%= image_tag recomendacao.img, size: "200x200"%> </p>
    <span id = "name_album"><%=recomendacao.titulo%></span>
    <p style="color:white;">Recomendado por <a class="reference" href="">@<%=recomendacao.artista %></a></p>
    <br>
    <br>
    <br>
    <div class="image__overlay image__overlay--primary">
      <div class="image__title"> @<%=recomendacao.artista%></div>
      <p class="image__description">
          <%=recomendacao.desc%>
      </p>
      <%=link_to "Editar", recomendacao%>
  </div>
  </div>
  <% end %>



<script src="https://code.jquery.com/jquery-3.4.0.min.js" integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<button class="btn btn-success">
<%= link_to "Nova Recomendação", new_recomendacao_path, style:"color:white" %>
</button>

app/views/recomendacoes/new.html.erb
<br>
<center><h1 style ="color:white;">RecomendeMe</h1></center>

<%= render "form", recomendacao: @recomendacao %>

<br>
</div>

app/views/recomendacoes/show.html.erb
<!---
<p style="color: green"><%= notice %></p>

<%= render @recomendacao %>

<div>
  <%= link_to "Edit this recomendacao", edit_recomendacao_path(@recomendacao) %> |
  <%= link_to "Back to recomendacoes", recomendacoes_path %>

  <%= button_to "Destroy this recomendacao", @recomendacao, method: :delete %>
</div>

--->

<div>
  <%= link_to "Edit this recomendacao", edit_recomendacao_path(@recomendacao) %> |
  <%= link_to "Back to recomendacoes", recomendacoes_path %>

<%= button_to "Destroy this recomendacao", @recomendacao, method: :delete %>
</div>

<p style="color: green"><%= notice %></p>






<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="Somos uma Plataforma Web com o intuito de compartilhar Músicas, Livros, Filmes e divulgar artistas independentes de forma livre e gratutita">
    <meta name="robots" content="index, follow">
    
    <title>RecomendeMe</title>
<style>
    body{
    margin: 0;
    padding: 0;
    color: black;
    background-color:"";
    }
    .background{
    }
    .image-container{
        width:40vw;
        height: 60vh;
        background-color: #000;
    }
    .image-container img{
        width: 100%;
        height: 100%;
        object-fit: cover;
    }
</style>
    
    <style>
        


</style>
	
    

  

</head>
<body>


<br>
<br>

<div class="background">



<center><h1 style="color:white;">Álbum</h1></center>

<center> <h5 style="color:white;">Recomendado por <a class="reference" href="">@<%=@recomendacao.artista%></a></h5></center>


<br>


<div class="imagem">
    
    <center><p> <%= image_tag @recomendacao.img, size: "300x300" %></p></center>
</div>
</div>
<br>
<br>
<p style="color:white; text-align:center;"> 
  <%= @recomendacao.titulo%></p>
<br>

	
	<center><a href="users.html"><button type='submit' class='btn btn-primary'>Ver outros Álbuns!</button></a></center>
	<br>
	<br>
	</div>
</div>



<!-- Global site tag (gtag.js) - Google Analytics -->



<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/color-thief/2.3.0/color-thief.umd.js"></script>


<script>
let sourceImage = document.querySelector("img");

</script>
</body>